import { supabase, SUPABASE_URL, SUPABASE_ANON_KEY } from './supabase'

/* Seasonal themes for the customer app (supabase-fix133.sql).

   The office header already schedules a decorative banner; this is the same
   idea carried into the customer's phone, and further: as well as a background
   movie it repaints the app. The super admin picks one of the themes below,
   uploads a clip authored for a phone screen, and gives it a date window —
   Ramadan, Christmas, the height of summer.

   Only the ROLE colours change. The app paints with three of them (see
   tailwind.config.js): `shop` carries the actions, `fresh` the confirmations,
   `accent` the highlights. They resolve through CSS variables, so a theme is a
   handful of custom properties set on the root element and every existing
   class follows — no component knows a theme exists.

   Nothing here is required: with no theme scheduled the app looks exactly as
   it always has. */

/* ── the palette machinery ───────────────────────────────────────────────
   A theme is described by three seed colours, not by twenty-two. The ramp is
   generated by mixing the seed toward white and black, which keeps every theme
   internally consistent and makes adding one a three-colour job. */

const clamp = n => Math.max(0, Math.min(255, Math.round(n)))

export function hexToRgb(hex) {
  const h = String(hex || '').replace('#', '').trim()
  const full = h.length === 3 ? h.split('').map(c => c + c).join('') : h
  const n = parseInt(full, 16)
  if (!Number.isFinite(n) || full.length !== 6) return [0, 0, 0]
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255]
}

export const rgbToHex = ([r, g, b]) =>
  '#' + [r, g, b].map(v => clamp(v).toString(16).padStart(2, '0')).join('')

/* mix(a, b, t): t = 0 → a, t = 1 → b. */
const mix = (a, b, t) => a.map((v, i) => clamp(v + (b[i] - v) * t))

const WHITE = [255, 255, 255]
const BLACK = [17, 17, 17]

/* 50…900 from one seed. 600 is the seed itself — the app's primary weight. */
export function ramp(seedHex) {
  const seed = hexToRgb(seedHex)
  return {
    50:  mix(seed, WHITE, 0.94),
    100: mix(seed, WHITE, 0.86),
    200: mix(seed, WHITE, 0.70),
    300: mix(seed, WHITE, 0.50),
    400: mix(seed, WHITE, 0.28),
    500: mix(seed, WHITE, 0.12),
    600: seed,
    700: mix(seed, BLACK, 0.18),
    800: mix(seed, BLACK, 0.36),
    900: mix(seed, BLACK, 0.55),
  }
}

/* ── the themes ──────────────────────────────────────────────────────────
   `shop` is the action colour, `fresh` confirms, `accent` highlights, and
   `ground` is the page behind everything. The default reproduces the palette
   the app ships with, so "no theme" and "Pomegranate" are the same thing. */

export const DEFAULT_THEME = {
  key: 'default',
  name: 'Pomegranate & Olive',
  note: 'The everyday look — used whenever nothing is scheduled.',
  season: 'default',
  shop: '#B3122B', fresh: '#5A6E3A', accent: '#E4B429', ground: '#FFF8EF',
  /* Hand-tuned rather than generated: the shipped palette sets its lightest
     shop weights to a warm CREAM, which no amount of mixing pomegranate with
     white would produce. Spelling them out keeps "no theme scheduled" pixel
     for pixel what the app has always looked like. */
  shopRamp: {
    50: '#FFF8EF', 100: '#FDEBE4', 200: '#F6CFC4', 300: '#EDA396', 400: '#DC6A5C',
    500: '#C1272D', 600: '#B3122B', 700: '#8E0F22', 800: '#6B0B19', 900: '#4A0711',
  },
  freshRamp: {
    50: '#F3F5EC', 100: '#E4E9D6', 200: '#C9D3AD', 300: '#A8B77F', 400: '#859B57',
    500: '#6B8043', 600: '#5A6E3A', 700: '#45542C', 800: '#333F21', 900: '#232C17',
  },
  accentRamp: { 400: '#EFCB5C', 500: '#E4B429', 600: '#C2951A' },
}

export const CUSTOMER_THEMES = [
  DEFAULT_THEME,
  // ── seasons ───────────────────────────────────────────────────────────
  { key: 'ocean_blue',     name: 'Ocean blue',     season: 'season',
    note: 'Deep sea blue, foam teal, sand.',
    shop: '#0369A1', fresh: '#0E7490', accent: '#38BDF8', ground: '#F2F9FD' },
  { key: 'summer_heat',    name: 'Summer heat',    season: 'season',
    note: 'Sun orange, palm green, bright yellow.',
    shop: '#EA580C', fresh: '#15803D', accent: '#FACC15', ground: '#FFF8ED' },
  { key: 'spring_blossom', name: 'Spring blossom', season: 'season',
    note: 'Blossom pink, new-leaf green, soft gold.',
    shop: '#DB2777', fresh: '#4D7C0F', accent: '#F9A8D4', ground: '#FFF5F9' },
  { key: 'autumn_fall',    name: 'Autumn / Fall',  season: 'season',
    note: 'Rust, moss, amber.',
    shop: '#B45309', fresh: '#4D7C0F', accent: '#D97706', ground: '#FDF7EE' },
  // ── holidays ──────────────────────────────────────────────────────────
  { key: 'christmas',      name: 'Christmas',      season: 'holiday',
    note: 'Christmas red, pine green, gold.',
    shop: '#B91C1C', fresh: '#166534', accent: '#EAB308', ground: '#FFF6F5' },
  { key: 'palm_sunday',    name: 'Palm Sunday',    season: 'holiday',
    note: 'Palm green, olive, soft gold.',
    shop: '#15803D', fresh: '#4D7C0F', accent: '#CA8A04', ground: '#F5FBF5' },
  { key: 'easter',         name: 'Easter',         season: 'holiday',
    note: 'Lilac, spring green, pastel yellow.',
    shop: '#7C3AED', fresh: '#16A34A', accent: '#FDE047', ground: '#FAF7FF' },
  { key: 'ramadan',        name: 'Ramadan',        season: 'holiday',
    note: 'Night indigo, lantern gold, crescent cream.',
    shop: '#4C1D95', fresh: '#0F766E', accent: '#D4A017', ground: '#FBF7F0' },
  { key: 'eid_al_fitr',    name: 'Eid al-Fitr',    season: 'holiday',
    note: 'Festive teal, gold, sweet pink.',
    shop: '#0D9488', fresh: '#15803D', accent: '#EAB308', ground: '#F2FBF9' },
  { key: 'eid_al_adha',    name: 'Eid al-Adha',    season: 'holiday',
    note: 'Deep emerald, sand, burnished gold.',
    shop: '#065F46', fresh: '#166534', accent: '#B45309', ground: '#F3FAF6' },
]

export const themeByKey = (key) =>
  CUSTOMER_THEMES.find(t => t.key === key) || DEFAULT_THEME

/* The CSS custom properties one theme sets. Values are "r g b" triplets so
   Tailwind's `rgb(var(--shop-600) / <alpha-value>)` keeps every /10, /40
   opacity variant working. */
export function themeVariables(themeKey) {
  const t = themeByKey(themeKey)
  const vars = {}
  // A theme may spell its ramp out; otherwise it is generated from the seed.
  const put = (role, hex, explicit) => {
    const r = explicit
      ? Object.fromEntries(Object.entries(explicit).map(([w, h]) => [w, hexToRgb(h)]))
      : ramp(hex)
    for (const [weight, rgb] of Object.entries(r)) vars[`--${role}-${weight}`] = rgb.join(' ')
  }
  put('shop', t.shop, t.shopRamp)
  put('fresh', t.fresh, t.freshRamp)
  /* The highlight is given as its 500 — that is the weight the app paints with
     — so it is used as it was written rather than lightened into something the
     designer never picked. */
  const acc = ramp(t.accent)
  vars['--accent-400'] = hexToRgb(t.accentRamp?.[400] || rgbToHex(acc[400])).join(' ')
  vars['--accent-500'] = hexToRgb(t.accentRamp?.[500] || t.accent).join(' ')
  vars['--accent-600'] = hexToRgb(t.accentRamp?.[600] || rgbToHex(acc[700])).join(' ')
  vars['--app-ground'] = hexToRgb(t.ground).join(' ')
  return vars
}

/* Paint (or unpaint) the app. Applied to the customer app's own root so the
   office console — which shares the stylesheet — is never repainted. */
export function applyCustomerTheme(themeKey, el = null) {
  const target = el || (typeof document !== 'undefined' ? document.documentElement : null)
  if (!target) return
  const vars = themeVariables(themeKey)
  for (const [k, v] of Object.entries(vars)) target.style.setProperty(k, v)
}

export function clearCustomerTheme(el = null) {
  const target = el || (typeof document !== 'undefined' ? document.documentElement : null)
  if (!target) return
  for (const k of Object.keys(themeVariables(DEFAULT_THEME.key))) target.style.removeProperty(k)
}

/* Swatches for the office picker — the five colours that carry a theme. */
export const themeSwatches = (key) => {
  const t = themeByKey(key)
  return [t.shop, t.fresh, t.accent, t.ground]
}

/* ── the schedule ────────────────────────────────────────────────────────
   Same shape as the office header banner (fix109/fix124/fix125): a row per
   scheduled theme, a date window, and media kept in storage as a URL rather
   than inside the row. */

export const MEDIA_BUCKET = 'header-media'          // shared with the office banner
export const MAX_VIDEO_KB = 30000
/* Above this a clip is worth questioning rather than refusing: it is a
   decorative loop on a phone, often over mobile data, and it has to upload from
   here first. */
export const ADVISED_VIDEO_KB = 8000
export const MAX_POSTER_KB = 2000

/* Authored for a phone held upright — anything else is cropped to fill. */
export const THEME_MEDIA_SIZE = { width: 1080, height: 1920 }

export const isStoredUpload = (url = '') =>
  /^https?:\/\//i.test(url) && url.includes(`/${MEDIA_BUCKET}/`)

const extOf = (file) => {
  const fromName = String(file?.name || '').split('.').pop()
  if (fromName && fromName.length <= 5 && /^[a-z0-9]+$/i.test(fromName)) return fromName.toLowerCase()
  return (String(file?.type || '').split('/').pop() || 'bin').toLowerCase()
}

const mb = (bytes) => (bytes / 1024 / 1024).toFixed(1)

/* Upload a clip (or poster) and hand back its public URL. The file stays OUT
   of the row: the phone streams it from storage and caches it, instead of
   dragging a base64 copy down on every start.

   Sent over XHR rather than the client's own upload for one reason: a 20 MB
   clip takes real time, and a form that looks frozen for two minutes is a form
   people give up on. XHR reports progress; fetch does not. It also lets a
   dropped connection be named as such — the browser's own words for it are
   "Failed to fetch", which tells the person nothing about what to do next. */
export function uploadThemeMedia(file, { onProgress = null } = {}) {
  if (!file) return Promise.resolve({ url: '', error: 'No file chosen.' })
  const stamp = new Date().toISOString().replace(/[-:T.]/g, '').slice(0, 14)
  const rand  = Math.random().toString(36).slice(2, 8)
  const path  = `customer-themes/${stamp}-${rand}.${extOf(file)}`
  const endpoint = `${SUPABASE_URL}/storage/v1/object/${MEDIA_BUCKET}/${path}`
  const publicUrl = `${SUPABASE_URL}/storage/v1/object/public/${MEDIA_BUCKET}/${path}`

  return new Promise((resolve) => {
    try {
      const xhr = new XMLHttpRequest()
      xhr.open('POST', endpoint, true)
      xhr.setRequestHeader('apikey', SUPABASE_ANON_KEY)
      xhr.setRequestHeader('authorization', `Bearer ${SUPABASE_ANON_KEY}`)
      xhr.setRequestHeader('x-upsert', 'false')
      xhr.setRequestHeader('cache-control', 'max-age=31536000')
      if (file.type) xhr.setRequestHeader('content-type', file.type)

      xhr.upload.onprogress = (ev) => {
        if (!onProgress) return
        onProgress(ev.lengthComputable ? Math.round((ev.loaded / ev.total) * 100) : null)
      }

      xhr.onload = () => {
        if (xhr.status >= 200 && xhr.status < 300) { resolve({ url: publicUrl, error: null }); return }
        let msg = ''
        try { msg = JSON.parse(xhr.responseText || '{}').message || '' } catch { msg = xhr.responseText || '' }
        const lower = msg.toLowerCase()
        resolve({
          url: '',
          error:
            /bucket not found|nosuchbucket/.test(lower)
              ? 'The header-media bucket isn’t there — run supabase-fix133.sql (or fix125), then upload again.'
            : /mime|invalid_mime_type/.test(lower)
              ? `That file type (${file.type || 'unknown'}) isn’t allowed. Use MP4 or WebM for a clip, JPG/PNG/WebP for a poster.`
            : /exceeded|too large|payload/.test(lower)
              ? `The file is ${mb(file.size)} MB — larger than storage will accept. Export a shorter or smaller clip.`
            : (msg || `Upload failed (HTTP ${xhr.status}).`),
        })
      }

      // No status at all: the request never completed — the connection dropped,
      // or the file was too big for the link to carry before something gave up.
      xhr.onerror = () => resolve({
        url: '',
        error: `The upload didn’t reach the server (${mb(file.size)} MB). `
             + 'This is usually the connection giving up on a large file — try a shorter or smaller clip, '
             + 'or paste a link to one already hosted.',
      })
      xhr.ontimeout = () => resolve({
        url: '',
        error: `The upload timed out at ${mb(file.size)} MB. Try a shorter clip, or paste a link to a hosted one.`,
      })
      xhr.onabort = () => resolve({ url: '', error: 'Upload cancelled.' })

      xhr.send(file)
    } catch (e) {
      resolve({ url: '', error: e?.message || 'Upload failed.' })
    }
  })
}

/* Best-effort tidy-up; an orphaned file is a nuisance, a theme that refuses to
   disappear is a bug. */
export async function removeThemeMedia(url) {
  if (!isStoredUpload(url)) return
  const path = url.split(`/${MEDIA_BUCKET}/`).pop()?.split('?')[0]
  if (!path) return
  try { await supabase.storage.from(MEDIA_BUCKET).remove([decodeURIComponent(path)]) } catch { /* ignore */ }
}

/* Is this theme the one to show right now? Dates are days, not moments: a
   theme "until 25/12" covers the whole of Christmas Day. */
export function isCurrent(row, today = new Date()) {
  if (!row || row.is_active === false) return false
  const day = typeof today === 'string' ? today : today.toISOString().slice(0, 10)
  if (row.starts_on && day < row.starts_on) return false
  if (row.ends_on   && day > row.ends_on)   return false
  return true
}

/* The theme to display, or null.

   The MOST SPECIFIC live row wins, not simply the newest: a dated occasion
   beats an open-ended everyday theme, and a short window beats a long one.
   Otherwise a theme left running all year would quietly swallow Christmas.
   Between two equally specific windows the newer decision is the deliberate
   one. */
const windowRank = (row) => {
  const both = row.starts_on && row.ends_on
  if (both) {
    const days = (new Date(row.ends_on) - new Date(row.starts_on)) / 86400000
    return [0, Number.isFinite(days) ? days : 9999]
  }
  if (row.starts_on || row.ends_on) return [1, 9999]
  return [2, 99999]                                   // open-ended: the fallback look
}

export function pickCurrent(rows, today = new Date()) {
  const live = (rows ?? []).filter(r => isCurrent(r, today))
  if (live.length === 0) return null
  return live.slice().sort((a, b) => {
    const [ka, da] = windowRank(a)
    const [kb, db] = windowRank(b)
    if (ka !== kb) return ka - kb
    if (da !== db) return da - db
    return new Date(b.created_at || 0).getTime() - new Date(a.created_at || 0).getTime()
  })[0]
}

const tableMissing = (msg = '') =>
  /customer_themes/i.test(msg) && /not exist|schema cache/i.test(msg)

/* "Failed to fetch" is the browser's words for "the request never completed",
   and it tells the reader nothing about what to do. Anything that reaches the
   server — including a rejection — comes back with a real message; this only
   rewrites the case where nothing did. */
const friendly = (msg = '') =>
  /failed to fetch|networkerror|load failed/i.test(msg)
    ? 'The request didn’t reach the server. Check the connection and try again — nothing was saved.'
    : msg

export async function fetchCustomerThemes(companyId = null) {
  try {
    let q = supabase.from('customer_themes').select('*').order('created_at', { ascending: false })
    if (companyId) q = q.eq('company_id', companyId)
    const { data, error } = await q
    if (error) return { rows: [], missing: tableMissing(error.message), error: friendly(error.message) }
    return { rows: data ?? [], missing: false, error: null }
  } catch (e) {
    return { rows: [], missing: false, error: friendly(e?.message || '') || 'Could not load themes.' }
  }
}

export async function saveCustomerTheme(row, { companyId = null, userId = null } = {}) {
  const payload = {
    theme_key:  row.theme_key || DEFAULT_THEME.key,
    name:       row.name?.trim() || null,
    media_url:  row.media_url || null,
    media_type: row.media_url ? 'video' : null,
    poster_url: row.poster_url || null,
    starts_on:  row.starts_on || null,
    ends_on:    row.ends_on   || null,
    overlay:    Number(row.overlay ?? 0.55),
    is_active:  row.is_active !== false,
    updated_at: new Date().toISOString(),
  }
  try {
    if (row.id) {
      const { error } = await supabase.from('customer_themes').update(payload).eq('id', row.id)
      return error ? friendly(error.message) : null
    }
    const { error } = await supabase.from('customer_themes').insert([{
      ...payload,
      ...(companyId ? { company_id: companyId } : {}),
      created_by: userId,
    }])
    return error ? friendly(error.message) : null
  } catch (e) {
    return friendly(e?.message || '') || 'Could not save the theme.'
  }
}

export async function deleteCustomerTheme(id) {
  const { error } = await supabase.from('customer_themes').delete().eq('id', id)
  return error ? error.message : null
}
